import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { useAccount } from "wagmi";
import { createProfile } from "../../utils/lensQueries";
import { useRouter } from "next/router";

export default function Step2() {
  const router = useRouter();

  const { address } = useAccount();

  const [lensHandle, setLensHandle] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();
    // console.log("HANDLE", lensHandle)
    // await login();

    const request = {
      handle: lensHandle,
    };
    const response = await createProfile(request);
    console.log("CREATED PROFILE?", response);
  };

  return (
    <div>
      <Head>
        <title>Step 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto mt-16 max-w-7xl px-4 sm:mt-24 sm:px-6">
        <div className="text-center sm:mx-auto sm:w-full sm:max-w-md">
          <h2 className="mt-6 text-center text-3xl font-bold tracking-tight text-gray-900">
            Create your Lens profile
          </h2>
          <p className="mt-2 text-center text-sm text-gray-600">
            Join the user-owned, decentralized web and grow your roots with
            Lens.
          </p>
          <div className="mx-auto mt-5 md:mt-8">
            <form className="">
              <div className="flex flex-col items-center mb-5 md:mb-8">
                <label
                  htmlFor="photo"
                  className="block text-sm font-medium text-gray-700 sr-only"
                >
                  Photo
                </label>
                <span className="h-12 w-12 overflow-hidden rounded-full bg-gray-100">
                  <svg
                    className="h-full w-full text-gray-300"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path d="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z" />
                  </svg>
                </span>
                <button
                  type="button"
                  className="rounded-md border border-gray-300 bg-white py-2 px-3 text-sm font-medium leading-4 text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                >
                  Upload
                </button>
              </div>

              <label
                htmlFor="username"
                className="block text-sm font-medium text-gray-700"
              >
                Your handle
              </label>
              <input
                type="text"
                name="username"
                id="username"
                autoComplete="username"
                className="block w-full min-w-0 flex-1 rounded-none rounded-r-md border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
              />

              <button
                type="button"
                className="inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
              >
                Create Lens profile
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
}
