import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { useAccount } from "wagmi";
import { useRouter } from "next/router";
import Layout from "../../components/layout/Layout";

// TODO: ignore
export default function Step3() {
  const router = useRouter();

  const { address } = useAccount();

  const [lensHandle, setLensHandle] = useState("");

  return (
    <Layout>
      <Head>
        <title>Make your homebase cozy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto my-8 max-w-7xl px-4 sm:my-12 sm:px-6">
        <div className="mx-auto max-w-md sm:max-w-3xl">
          <h2 className="text-center text-3xl leading-8 text-emerald-900 sm:text-4xl font-cursive font-normal">
            Make your homebase cozy
          </h2>
          <p className="mx-auto mt-4 max-w-3xl text-center text-xl text-stone-600">
            Dropping some alpha? Sharing your works in progress? Releasing
            exclusive bonus content? Let your fans know what to expect when they
            come chill at your homebase.
          </p>
          <div className="mx-auto w-full sm:max-w-md mt-5 md:mt-8">
            <form className="space-y-12">
              <div>
                <label
                  htmlFor="about"
                  className="block font-medium text-stone-700"
                >
                  What&apos;s poppin&apos; at your homebase?
                </label>
                <div className="mt-2">
                  <textarea
                    id="about"
                    name="about"
                    rows={3}
                    className="block w-full rounded-md border-stone-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500 sm:text-sm"
                    defaultValue={""}
                  />
                </div>
              </div>

              <div className="text-center">
                <button
                  type="submit"
                  className="inline-flex items-center rounded-md border border-transparent bg-emerald-700 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-emerald-700 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2"
                >
                  Continue
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </Layout>
  );
}
