import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { useAccount } from "wagmi";
import { ethers } from "ethers";
import { generateChallenge, authenticate } from "../../utils/lensQueries";
import { useRouter } from "next/router";
import Layout from "../../components/layout/Layout";
import { loginWithLens } from "../../utils/lensHub";

export default function Step1() {
  const router = useRouter();

  const { address } = useAccount();

  const login = async () => {
    try {
      await loginWithLens();
      router.push("/create/step2");
    } catch (error) {
      console.log("ERROR", error);
    }
  };

  return (
    <Layout>
      <Head>
        <title>Connect to Lens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto my-8 max-w-7xl px-4 sm:my-12 sm:px-6">
        <div className="mx-auto max-w-md sm:max-w-3xl">
          <h1 className="text-center text-3xl leading-8 text-emerald-900 sm:text-4xl font-cursive font-normal">
            Connect to Lens
          </h1>
          <p className="mx-auto mt-4 max-w-3xl text-center text-xl text-stone-500">
            Your homebase is powered by Lens, the composable and decentralized
            social graph of web3. Connect to Lens to get started.
          </p>
          <div className="mx-auto mt-5 max-w-md sm:flex sm:justify-center md:mt-8">
            <button
              type="button"
              onClick={login}
              className="inline-flex items-center rounded-md border border-transparent bg-emerald-700 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-emerald-800 focus:outline-none focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2"
            >
              Connect to Lens
            </button>
          </div>
        </div>
      </div>
    </Layout>
  );
}
