import Head from 'next/head'
import Image from 'next/image'
import UploadContent from '../components/UploadContent'

export default function Home() {
  return (
    <div>
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <h1 className="text-3xl font-bold underline">
      Home
    </h1>

     <UploadContent/>
    </div>
  )
}
