import Head from 'next/head'
import Image from 'next/image'
import CreateLensProfile from '../components/CreateLensProfile'
import { ping } from '../utils/lensQueries' 


export default function Home() {
  return (
    <div>
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <h1 className="text-3xl font-bold underline">
      Home
    </h1>

    <CreateLensProfile/>

    <button onClick={async () => {
      let resp = await ping()
      console.log("PING", resp)
    }}>Ping Lens Health</button>

   
    </div>
  )
}
